source 'https://rubygems.org'

# Jekyll
gem "jekyll", ">= 3.0.0"
gem "jekyll-coffeescript"
gem "jekyll-sass-converter"

# Converters
gem "kramdown"
gem "maruku"
gem "rdiscount"
gem "redcarpet"
gem "RedCloth"

# Liquid
gem "liquid"

# Highlighters
gem "pygments.rb"

# Plugins
#gem "jemoji"
#gem "jekyll-mentions"
gem "jekyll-redirect-from", ">= 0.9.0"
gem "jekyll-sitemap"
